INSERT INTO dbo."Comuna"(codigo, descripcion) VALUES ('13101', 'Santiago');
INSERT INTO dbo."Comuna"(codigo, descripcion) VALUES ('13102', 'Cerrillos');
INSERT INTO dbo."Comuna"(codigo, descripcion) VALUES ('13103', 'Cerro Navia');
INSERT INTO dbo."Comuna"(codigo, descripcion) VALUES ('13104', 'Conchalí');
INSERT INTO dbo."Comuna"(codigo, descripcion) VALUES ('13105', 'El Bosque');
INSERT INTO dbo."Comuna"(codigo, descripcion) VALUES ('13106', 'Estación Central');
INSERT INTO dbo."Comuna"(codigo, descripcion) VALUES ('13107', 'Huechuraba');
INSERT INTO dbo."Comuna"(codigo, descripcion) VALUES ('13108', 'Independencia');
INSERT INTO dbo."Comuna"(codigo, descripcion) VALUES ('13109', 'La Cisterna');
INSERT INTO dbo."Comuna"(codigo, descripcion) VALUES ('13110', 'La Florida');
INSERT INTO dbo."Comuna"(codigo, descripcion) VALUES ('13111', 'La Granja');
INSERT INTO dbo."Comuna"(codigo, descripcion) VALUES ('13112', 'La Pintana');
INSERT INTO dbo."Comuna"(codigo, descripcion) VALUES ('13113', 'La Reina');
INSERT INTO dbo."Comuna"(codigo, descripcion) VALUES ('13114', 'Las Condes');
INSERT INTO dbo."Comuna"(codigo, descripcion) VALUES ('13115', 'Lo Barnechea');
INSERT INTO dbo."Comuna"(codigo, descripcion) VALUES ('13116', 'Lo Espejo');
INSERT INTO dbo."Comuna"(codigo, descripcion) VALUES ('13117', 'Lo Prado');
INSERT INTO dbo."Comuna"(codigo, descripcion) VALUES ('13118', 'Macul');
INSERT INTO dbo."Comuna"(codigo, descripcion) VALUES ('13119', 'Maipú');
INSERT INTO dbo."Comuna"(codigo, descripcion) VALUES ('13120', 'Ñuñoa');
INSERT INTO dbo."Comuna"(codigo, descripcion) VALUES ('13121', 'Pedro Aguirre Cerda');
INSERT INTO dbo."Comuna"(codigo, descripcion) VALUES ('13122', 'Peñalolén');
INSERT INTO dbo."Comuna"(codigo, descripcion) VALUES ('13123', 'Providencia');
INSERT INTO dbo."Comuna"(codigo, descripcion) VALUES ('13124', 'Pudahuel');
INSERT INTO dbo."Comuna"(codigo, descripcion) VALUES ('13125', 'Quilicura');
INSERT INTO dbo."Comuna"(codigo, descripcion) VALUES ('13126', 'Quinta Normal');
INSERT INTO dbo."Comuna"(codigo, descripcion) VALUES ('13127', 'Recoleta');
INSERT INTO dbo."Comuna"(codigo, descripcion) VALUES ('13128', 'Renca');
INSERT INTO dbo."Comuna"(codigo, descripcion) VALUES ('13129', 'San Joaquín');
INSERT INTO dbo."Comuna"(codigo, descripcion) VALUES ('13130', 'San Miguel');
INSERT INTO dbo."Comuna"(codigo, descripcion) VALUES ('13131', 'San Ramón');
INSERT INTO dbo."Comuna"(codigo, descripcion) VALUES ('13132', 'Vitacura');
INSERT INTO dbo."Comuna"(codigo, descripcion) VALUES ('13201', 'Puente Alto');
INSERT INTO dbo."Comuna"(codigo, descripcion) VALUES ('13202', 'Pirque');
INSERT INTO dbo."Comuna"(codigo, descripcion) VALUES ('13203', 'San José de Maipo');
INSERT INTO dbo."Comuna"(codigo, descripcion) VALUES ('13301', 'Colina');
INSERT INTO dbo."Comuna"(codigo, descripcion) VALUES ('13302', 'Lampa');
INSERT INTO dbo."Comuna"(codigo, descripcion) VALUES ('13303', 'Tiltil');
INSERT INTO dbo."Comuna"(codigo, descripcion) VALUES ('13401', 'San Bernardo');
INSERT INTO dbo."Comuna"(codigo, descripcion) VALUES ('13402', 'Buin');
INSERT INTO dbo."Comuna"(codigo, descripcion) VALUES ('13403', 'Calera de Tango');
INSERT INTO dbo."Comuna"(codigo, descripcion) VALUES ('13404', 'Paine');
INSERT INTO dbo."Comuna"(codigo, descripcion) VALUES ('13501', 'Melipilla');
INSERT INTO dbo."Comuna"(codigo, descripcion) VALUES ('13502', 'Alhué');
INSERT INTO dbo."Comuna"(codigo, descripcion) VALUES ('13503', 'Curacaví');
INSERT INTO dbo."Comuna"(codigo, descripcion) VALUES ('13504', 'María Pinto');
INSERT INTO dbo."Comuna"(codigo, descripcion) VALUES ('13505', 'San Pedro');
INSERT INTO dbo."Comuna"(codigo, descripcion) VALUES ('13601', 'Talagante');
INSERT INTO dbo."Comuna"(codigo, descripcion) VALUES ('13602', 'El Monte');
INSERT INTO dbo."Comuna"(codigo, descripcion) VALUES ('13603', 'Isla de Maipo');
INSERT INTO dbo."Comuna"(codigo, descripcion) VALUES ('13604', 'Padre Hurtado');
INSERT INTO dbo."Comuna"(codigo, descripcion) VALUES ('13605', 'Peñaflor');


